apiVersion: v1
kind: Pod
metadata:
  name: asp-pod
  labels:
    app: asp-pod
  namespace: default
spec:
  securityContext:
    runAsNonRoot: false
  containers:
    - name: ngc-pod
      image: 'harbor.sti.demo/sti/aspnetapp:v1'
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "2Gi"
          cpu: "4"
        requests:
          memory: "2Gi"
          cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: asp-svc                   
  labels:                       
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  selector:
    app: asp-pod
  ports:
  - name: http
    protocol: TCP
    port: 80 
    targetPort: 80
  type: NodePort
